development:
  forest_env_secret: 1cb34c2552c06237582629f5aa0100cb7254ea720cad519d26874b28268dad77
  forest_auth_secret: uXUUUyIkujMAU7ddF77amA
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
